server.port=8080

# H2 Database salvato su file locale dentro il progetto
spring.datasource.url=jdbc:h2:file:./data/turnidb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.auto_quote_keyword=true

# Configurazione Timefold: calcolo per massimo 5 secondi
timefold.solver.termination.spent-limit=5s

logging.level.org.springframework=INFO